// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCISjIKMCiUKZQhdUoZRVvYi9fRyiXn7ho',
    appId: '1:48180638638:web:882f5315e5de7346b54e3f',
    messagingSenderId: '48180638638',
    projectId: 'furniture-fa597',
    authDomain: 'furniture-fa597.firebaseapp.com',
    storageBucket: 'furniture-fa597.appspot.com',
    measurementId: 'G-Q2JPJ7TST2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL8S6zs-uBOQhNfFNRys0yFekYsy0zQTY',
    appId: '1:923170883929:web:4a25236be4c90c0254a448',
    messagingSenderId: '923170883929',
    projectId: 'push-notification-d254d',
    authDomain: 'push-notification-d254d.firebaseapp.com',
    storageBucket: 'push-notification-d254d.appspot.com',
    measurementId: 'G-SM8070YLN8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZigROtsbEyuSqPwRXdsXbikc-3VXz8fk',
    appId: '1:923170883929:ios:7184c1b55e8fb01f54a448',
    messagingSenderId: '923170883929',
    projectId: 'push-notification-d254d',
    storageBucket: 'push-notification-d254d.appspot.com',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyLntUy-BZVgQdxntfv8v6u6-tRAoPANA',
    appId: '1:923170883929:android:efc5d87a9b82a8fe54a448',
    messagingSenderId: '923170883929',
    projectId: 'push-notification-d254d',
    storageBucket: 'push-notification-d254d.appspot.com',
  );

}