// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCISjIKMCiUKZQhdUoZRVvYi9fRyiXn7ho',
    appId: '1:48180638638:web:882f5315e5de7346b54e3f',
    messagingSenderId: '48180638638',
    projectId: 'furniture-fa597',
    authDomain: 'furniture-fa597.firebaseapp.com',
    storageBucket: 'furniture-fa597.appspot.com',
    measurementId: 'G-Q2JPJ7TST2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCISjIKMCiUKZQhdUoZRVvYi9fRyiXn7ho',
    appId: '1:48180638638:web:1533c5696fa712adb54e3f',
    messagingSenderId: '48180638638',
    projectId: 'furniture-fa597',
    authDomain: 'furniture-fa597.firebaseapp.com',
    storageBucket: 'furniture-fa597.appspot.com',
    measurementId: 'G-B6NXMHFSWL',
  );
}
